baseURL = 'https://world.tockos.org/tockworld7'
languageCode = 'en-us'
title = 'TockWorld 7'
theme = 'event'

[params]
date = "June 26-28, 2024"
location = "San Diego, CA"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[[menus.main]]
name = 'Venue'
pageRef = 'venue'
weight = 20

[[menus.main]]
name = 'Agenda'
pageRef = 'agenda'
weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
