baseURL = 'https://world.tockos.org/tockworld8'
languageCode = 'en-us'
title = 'TockWorld 8'
theme = 'event'

[params]
date = "June 26-28, 2024"
location = "San Diego, CA"

[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
