[build]
  publish = "public"
  command = "hugo -d public/tockworld8 --gc --minify"

  [build.environment]
    HUGO_VERSION = "0.121.1"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.split1]
  command = "hugo -d public/tockworld8 --gc --minify --enableGitInfo"

  [context.split1.environment]
    HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo -d public/tockworld8 --gc --minify --buildFuture -b $DEPLOY_PRIME_URL/tockworld8"

[context.branch-deploy]
  command = "hugo -d public/tockworld8 --gc --minify -b $DEPLOY_PRIME_URL/tockworld8"

[context.next.environment]
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/"
  to = "/tockworld8"
  status = 302
  force = true
