baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Fancy Event'

[params]
date = 'April 1st, 1960'
location = 'Earth'

[[menus.main]]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
