baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Fancy Event'

[params]
date = 'April 1st, 1960'
location = 'Earth'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
